### ISSUE TITLE
clean up roles for squad awards

### ISSUE THREAD

**Issue by meckleunn** [meckleunn/unnamed#11]
clean up squad awards 

Squiddy the Reaper [Top Monthly Killer]
Squiddy the Medic [Top Revives] 
Squiddy the Timekeeper [Top Time] 

Remove names, change to something related and catchy

Top Monthly Killer
Top Monthly Medic
Top Monthly Teamkiller 
Top Monthly Deaths 

pick relevant emojis

**Comment by M0dul** [comment]
### Role Update
>| renamed Squad Award roles
>| Updated Role Icons

>| added role "Top Monthly Deaths"
>| removed role "Turret Gunner in Training"

**Comment by M0dul** [comment]
Issue complete
