### ISSUE TITLE
Discord Rank Updates 

### ISSUE THREAD

**Issue by M0dul** [meckleunn/unnamed#2]
Overall rework of the rank System used by UNN Corp.

### Rank Updates
**SQUAD**

>| CEO of Squad reused for [SQ] Chief Administrative Officer
>| Director of Squad reused for [SQ] Executive Director
>| [SQ] Community Manager reused for [SQ] Community Director
>|  Created [SQ] Diplomacy Director
>|  Created [SQ] Events Director

**Star Citizen**
>|  Created [SC] Chief Administrative Officer
>|  Created [SC] Recruiting Director 
>|  Created [SC] Navy Director
>|  Created [SC] Industrial Director
>|  Created [SC] Engineering Director

**General**
>| Removed rank "red" do to space issues

**Comment by meckleunn** [comment]
add space [SQ]" "Community Director

Leave josef's kitten, just move downwards.

**Comment by M0dul** [comment]
>| cleaned up thread Issue complete
