### ISSUE TITLE
Work with ferb to start building infrastructure for his div 

### ISSUE THREAD

**Issue by meckleunn** [meckleunn/unnamed#22]
Work with ferb to start getting the industry section setup, including roles, goals. 

We will need to setup discord category as he desires, how the best to have membership entry, and roles for his section. 

Then we will need a list of goals wished for with our existing infrastructure, such as work order system, stats tracking or whatever desired. Corporate goal, make money, self sustain membership, provide material, salvage material, and do it perfect

**Comment by M0dul** [comment]
Started planing section awaiting response from ferb.

**Comment by M0dul** [comment]
complete
