### ISSUE TITLE
Redesign permissions, for admin logging

### ISSUE THREAD

**Issue by meckleunn** [meckleunn/unnamed#28]
build out logging area, to include archives to be put into archive category. 

https://discord.com/channels/836985182778556436/995089179191038092/1075907726556790864 

Based on this feedback, if general use is to remove the channel - we will archive, only visible to discord admins, archive at bottom of discord

**Comment by M0dul** [comment]
Priority 1

**Comment by M0dul** [comment]
### Locked

Channel send to archive:
FOBexplo - removed Visibility
https://discord.com/channels/836985182778556436/995089179191038092/1075907801811001454

sq-validator removal request to @meckleunn

**Comment by M0dul** [comment]
complete
