### ISSUE TITLE
add forums for divisions into one category for SC

### ISSUE THREAD

**Issue by meckleunn** [meckleunn/unnamed#3]
- Star Citizen Divisions
- > Division 1
- > 2 etc

**Comment by M0dul** [comment]
### Work progession

ongoing 
>| Created 2 Division spaces more will be added

**Comment by M0dul** [comment]
Section restructured with a test phase for Forum i need @meckleunn to approve this idea if not i will revoke changes

**Comment by meckleunn** [comment]
im not seeing it? Can you link me to forum

**Comment by M0dul** [comment]
Im gonna close this issue it will be condensed with issue #30
