### ISSUE TITLE
SC Managers need "Bucket Rank" 

### ISSUE THREAD

**Issue by meckleunn** [meckleunn/unnamed#40]

**Comment by meckleunn** [comment]
just like "SC Directors"

**Comment by meckleunn** [comment]
![image](https://user-images.githubusercontent.com/121976589/220840359-fe98a752-8c5c-4d6f-97fe-3f507ac5f2ca.png)

**Comment by M0dul** [comment]
Role Created

[SC] Management 

permissions will be updated later
