### ISSUE TITLE
channel permission fixing

### ISSUE THREAD

**Issue by meckleunn** [meckleunn/unnamed#6]
channel permissions need to be simplified

**Comment by M0dul** [comment]
### Star Citizen Area

>| Changed: added all Directors roles to kategory

**Comment by M0dul** [comment]
### Updated Channels

>| Valheim permissions update

**Comment by M0dul** [comment]
### Struckture Modified

>| Excluded SC Administration Section

**Comment by M0dul** [comment]
**Update Roles**

>| created teamroles for SC & SQ
>| pending creation divison roles for SC
